package uz.pdp.app_new_site.entity.enums;

public enum Huquq {

    // LAVOYILAR DINAMIK BO'LISHI MUMKIN,  AMMO BU HUQUQLAR AUTHORIZES STATIC BO'LADI VA TIZIMNI O'ZIDA SAQLANADI, DB DA EMAS

    // ADMIN HUQUQLARI
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    VIEW_USERS,

    // ADMIN HUQUQLARI
    ADD_LAVOZIM,
    EDIT_LAVOZIM,
    DELETE_LAVOZIM,
    VIEW_LAVOZIMLAR,

    // USER HUQUQLARI :   MASALAN MUHARRIR
    ADD_POST,     // ADMIN
    EDIT_POST,    // ADMIN
    DELETE_POST,  // ADMIN

    // VIEW_POST,  HUQUQI  BO'LMAYDI CHUNKI IXTIYORIY ODAM MAQOLANI KO'RISHI MUMKIN, USER OQISH U-N REGISTER BOLISHISHART EMAS

    // ODDIY O'QUVCHINING  HUQUQLARI,
    ADD_COMMENT,         // ALL     HAMMA  MAQOLAGA IZOH  YOZISHI MUMKIN
    EDIT_COMMENT,        // ALL     MENI COMMENTIMINI FAQAT O'ZIM O'ZGARTIRAMAN, ADMIN O'CHIRISHI MUMKIN
    DELETE_MY_COMMENT,   // ALL

    // ADMIN HUQUQLARI , YOKI MUHARRIR SIFATIDA SAVE QILINGAN USER
    DELETE_COMMENT,

}
